version: "3.8"

services:
  redis:
    image: redis:6.2
    container_name: redis_service
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s  # Increased timeout
      retries: 5  # Increased retries
    networks:
      - app_network

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app_service
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    entrypoint: ["./wait-for-it.sh", "redis:6379", "--", "flask", "run", "--host=0.0.0.0", "--port=5000"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
