version: "3.8"

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app_service
    ports:
      - "5000:5000"
    environment:
      # No more Redis-related environment variables
    entrypoint: ["./wait-for-it.sh", "flask:5000", "--", "flask", "run", "--host=0.0.0.0", "--port=5000"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
