version: "3.8"

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app_service
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
